In [1]:
import numpy as np

<font size=4  face="微软雅黑">.ndim .shape .size</font>

In [2]:
array = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(array.ndim)
print(array.shape)
print(array.size)

2
(2, 3)
6


<font size=4  face="微软雅黑">.arange .zeros .linspace</font>

In [3]:
array = np.array([[1, 2, 3],
                 [4, 5, 6]], dtype=np.float)
array_zero = np.zeros((3, 4), dtype=np.int64)
print(array.dtype)
print(array_zero)
arange = np.arange(3, 4, 0.2)                       # np.arange()        [)
arange_1 = np.arange(12).reshape(3, 4)
print(arange)
print(arange_1)
lins = np.linspace(1, 10, 9)                        # np.linspace()      [] 
print(lins)

float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[3.  3.2 3.4 3.6 3.8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


<font size=4  face="微软雅黑">.dot .random</font>

In [4]:
a = np.array([[1, 1],
             [0, 1]])
b = np.arange(4).reshape(2, 2)
c = a*b
c_dot = np.dot(a, b)                                # a.dot(b)
print(c)
print(c_dot)
a = np.random.random((2,5))
print(a)
print(a.sum(axis=1))

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[0.95539814 0.62998772 0.1574326  0.02636014 0.34642783]
 [0.57618055 0.37980668 0.81582396 0.39814448 0.93242913]]
[2.11560643 3.10238479]


<font size=4  face="微软雅黑">.argmin .cumsum .diff .clip</font>

In [5]:
A =np.arange(2, 14).reshape(3, 4)
print(A)
idx = A.argmin()
print(idx)
c_sum = A.cumsum(axis=0)          #累加
print(c_sum)
diff = np.diff(A)
print(diff)
clip = np.clip(A, 7, 9)            #更改异常值
print(clip)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
[[ 2  3  4  5]
 [ 8 10 12 14]
 [18 21 24 27]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[7 7 7 7]
 [7 7 8 9]
 [9 9 9 9]]


<font size=4  face="微软雅黑">.T .flat for search index</font>

In [6]:
A = np.arange(3, 15).reshape(3, 4)
print(A)
print(A[2])
print(A[2, 3])
for column in A.T:
    print(column)
for item in A.flat:
    print(item, end=' ')

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
14
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3 4 5 6 7 8 9 10 11 12 13 14 

<font size=4  face="微软雅黑">.vstack .hstack .concatenate</font>

In [7]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
C = np.vstack((A,B))
print(C)
D = np.hstack((A, B))
print(D)
A_T = A.reshape(-1, 1)
B_T = B.reshape(-1, 1)
C_T = np.hstack((A_T, B_T, B_T))
print(C_T)
D_T = np.vstack((A_T, B_T))
print(D_T)
E = np.concatenate((A_T, A_T, B_T, B_T), axis=1)
print(E)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1 2 2]
 [1 2 2]
 [1 2 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 1 2 2]
 [1 1 2 2]
 [1 1 2 2]]


<font size=4  face="微软雅黑">.split .array_split</font>

In [8]:
A = np.arange(12).reshape(3, 4)
print(A)
B = np.split(A, 2, axis=1)
print(B)
C = np.array_split(A[:, 1:3], 3, axis=1)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([], shape=(3, 0), dtype=int32)]


<font size=4  face="微软雅黑">Test</font>

In [9]:
a = np.random.choice(np.random.randint(0, 9999, size=10), 10, replace=False)
b = a.argsort()
print(sorted(a))

[163, 1202, 1432, 2795, 3166, 4176, 5408, 5860, 8959, 9617]


In [10]:
a = np.arange(0, 5, 1)
b = np.zeros((5, 5))
for i in range(5):
    b[i] = a
print(b)
# print(np.array(list).transpose(1, 0))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [11]:
a = np.arange(0, 5, 1).reshape(1, -1)
b = a.transpose(1, 0)
c = np.meshgrid(a, a.transpose(1, 0))[0]
print(c)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
