In [1]:
import pandas as pd
import numpy as np

<font size=4  face="微软雅黑">.Series .DataFrame .date_range .sort_values</font>

In [3]:
s = pd.Series([1, 3, 6, np.nan, 44, 1])
print(s)
print(type(s[3]))                              #np.nan的type是float64
dates = pd.date_range('20160101', periods=6)
# dates = [1, 2, 3, 4, 5, 6]
print(type(dates))
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['a', 'b', 'c', 'd'])
# print(df)
# print(df.dtypes)
# print(df.index)
# print(df.columns)
# print(df.describe())
# df.info()
df = df.sort_values(by='b', ascending=False)   # True从小到大, False从大到小
print(df)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64
<class 'numpy.float64'>
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
                   a         b         c         d
2016-01-01  0.976769  1.216366  0.755488 -1.166876
2016-01-06  0.094132  0.709565 -0.219765 -0.501556
2016-01-04  1.648303 -0.058042 -1.361834 -1.106543
2016-01-05  0.765988 -0.332497 -0.539319  0.028315
2016-01-03  1.729746 -1.504915  1.112002  0.608256
2016-01-02 -1.669225 -1.787684  0.183072  1.186451


<font size=4  face="微软雅黑">Two</font>

In [28]:
columns = [chr(i) for i in np.arange(97, 105, 1)]
df = pd.DataFrame(np.random.randint(1, 100, size=40).reshape(5, 8), index=np.arange(0, 5, 1), columns=columns)
print(df)

    a   b   c   d   e   f   g   h
0  51  50  30  28  26  87  19  89
1  98  42  37  94  91  87  82  75
2  90  20  40  24  88  36  36  11
3  53   7  65  81  34  53  71  28
4  72  87  63  13   8  24  18  21


In [29]:
print(type(df.index))
print(type(df.columns))
print(type(df.values))
print(df.index)
print(df.columns)
print(df.values) 
df['a'] = ['aa', 'bb', 'cc', 'dd', 'ee']
df['a'] = df['a'].apply(lambda x: x.capitalize())
df['b'] = df['b'].apply(lambda x: '合法' if x > 75 else '不合法')
print(df)

<class 'pandas.core.indexes.numeric.Int64Index'>
<class 'pandas.core.indexes.base.Index'>
<class 'numpy.ndarray'>
Int64Index([0, 1, 2, 3, 4], dtype='int64')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')
[[51 50 30 28 26 87 19 89]
 [98 42 37 94 91 87 82 75]
 [90 20 40 24 88 36 36 11]
 [53  7 65 81 34 53 71 28]
 [72 87 63 13  8 24 18 21]]
    a    b   c   d   e   f   g   h
0  Aa  不合法  30  28  26  87  19  89
1  Bb  不合法  37  94  91  87  82  75
2  Cc  不合法  40  24  88  36  36  11
3  Dd  不合法  65  81  34  53  71  28
4  Ee   合法  63  13   8  24  18  21


In [22]:
df = pd.DataFrame({'a': [-71, 1, 2, 3, 4, 5, 6, 80]})
mean_a = df['a'].mean()
std_a = df['a'].std()
max_a = df['a'].max()
min_a = df['a'].min()
df_new = (df['a'] - mean_a) / std_a
df1 = (df['a'] - mean_a) / (max_a - min_a)
df2 = (df['a'] - min_a) / (max_a - min_a)
print(df1)
print(df_new)
print(df2)

0   -0.495033
1   -0.018212
2   -0.011589
3   -0.004967
4    0.001656
5    0.008278
6    0.014901
7    0.504967
Name: a, dtype: float64
0   -1.850703
1   -0.068086
2   -0.043327
3   -0.018569
4    0.006190
5    0.030948
6    0.055707
7    1.887841
Name: a, dtype: float64
0    0.000000
1    0.476821
2    0.483444
3    0.490066
4    0.496689
5    0.503311
6    0.509934
7    1.000000
Name: a, dtype: float64


In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>

In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>

In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>

In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>

In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>

In [ ]:
<font size=4  face="微软雅黑">.dot .random</font>